# Generated by Django 4.0 on 2021-12-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(help_text='format: xxx-xx-xx-xxx, required, unique', max_length=13, unique=True, verbose_name='Product Web Id')),
                ('slug', models.SlugField(help_text='format:required, letters, numbers, hyphens or underscores', max_length=255, verbose_name='Product Safe URL')),
                ('name', models.CharField(help_text='format: required, max_length=255', max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(verbose_name='Product Description')),
            ],
        ),
    ]
