# Generated by Django 4.0 on 2021-12-31 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='web_id',
            field=models.CharField(help_text='format: xxx-xx-xx-xxx, required, unique', max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\d\\d\\d-\\d\\d-\\d\\d-\\d\\d\\d$', 'Enter a valid web id.', 'invalid')], verbose_name='Product Website Id'),
        ),
    ]
